### ISSUE TITLE
fix to support npm 3.x

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integrations#48] opened 2015-09-30 17:02 UTC
The release of npm version 3.3.3 broke the `api` and `handler` builds ([Slack conversation](https://activeprospect.slack.com/archives/leadconduit/p1442608211001968)). 

It looks to me like the root problem – or the first one, anyway – is the way this package assumes it will have its integration modules installed (on [this line](https://github.com/activeprospect/leadconduit-integrations/blob/master/src/index.coffee#L31)). Because with npm 3.x, that's no longer the way it works when this package is a dependency (of, say, `api` or `handler`).

As the [npm 3.0.0 release notes](https://github.com/npm/npm/releases/tag/v3.0.0) explain:

> **Flat, flat, flat!**
> 
> Your dependencies will now be installed maximally flat. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's node_modules folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

Until this is fixed, the `api` and `handler` need to use `npm@2`.

**Comment by alexkwolfe** [comment] 2015-09-30 17:14
I don't get what that line has to do with it. It's merely getting the integration names out of the package.json.

**Comment by cgrayson** [comment] 2015-09-30 17:16
Oops, my bad. I found the wrong source line when I trace back from the `.js` to the `.coffee`. It's [this line](https://github.com/activeprospect/leadconduit-integrations/blob/master/src/index.coffee#L31) (updated the link above, too).

**Comment by alexkwolfe** [comment] 2015-09-30 17:19
Got it. That makes sense. We are going to be changing the way that integrations get loaded anyway, so my vote is for sticking with npm@2 until that time. This may become a non-issue.

**Comment by alexkwolfe** [comment] 2017-11-02 14:31
I change my vote. I think we should fix this. We can not upgrade to the latest Node LTS until this gets fixed. I'm nervous about this issue causing us to fall way behind in node releases.

**Comment by chasingSublimity** [comment] 2017-11-08 17:09
So the problem is actually [here](https://github.com/activeprospect/leadconduit-integrations/blob/master/src/index.coffee#L41), not line 25 as I originally thought. It's looking in the `node_modules` directory of `leadconduit-integrations`, which is mostly empty when installed by `npm@latest`.

The most forthcoming solution I've found is to change the path to access the root `node_modules` directory like so:
` pkg = require(path.join(__dirname, '..', '..', '..', name, 'package.json'));`

However, that smells kinda weird, and I'm not familiar enough with `api` or `handler` to know if that change will break anything. 

Any thoughts?

**Comment by alexkwolfe** [comment] 2017-11-08 17:22
Would it work to use `require.resolve` like below? It has the advantage of dynamically resolving the path to the integration rather than relying on it being installed in a particular spot, which is the cause of this issue to begin with.

```
pkg = require(path.join(require.resolve('@activeprospect/leadconduit-salesforce'), '..', 'package.json'))
```

**Comment by chasingSublimity** [comment] 2017-11-08 17:36
Sorry, I missed that comment in slack. `require.resolve()` solves the issue. 🎉

**Closed** 2017-11-20 18:13 UTC
Labels: bug
